### ISSUE TITLE
Modify input file parsing to accept new YAML fixture format

### ISSUE THREAD

**Issue by Spacecow99** [Spacecow99/complete_cs_instance#2]
During the PoC we used a hacked together JSON file but going forward we will be using a YAML format similar to `ciphersuite.info`'s fixtures. This should just be modifying the parser to use the `pk` key rather than `Description`, and a quick modification to the hexcode byte logic since this is already done. For now we will keep the `ciphersuite` namedtuple format to keep mimicking the `ciphersuite.info` function implementation.

**Comment by Spacecow99** [comment]
Initial changes to input/output YAML format made in 8d38aee. Still need to decide on the final YAML structure.

**Comment by Spacecow99** [comment]
Considering using a model similar to that from the iana scraper, pk is the full ciphersuite name and fields contain the parsed properties.

```yaml
- model: directory.Ciphersuite
  pk: TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384
  fields:
    hex_byte_1: '0xD0'
    hex_byte_2: '0x02'
    protocol_version: TLS
    old: false
    export: false
    fips: false
    kex_algorithm: ECDHE
    auth_algorithm: PSK
    enc_algorithm: AES 128 CCM
    aead_algorithm: true
    hash_algorithm: SHA256
```

Change made in commit [328498a](https://github.com/Spacecow99/complete_cs_instance/commit/328498ae41cacff474db713a565526534c9c93ce) for now.
